### PR TITLE
fix: change device name in devices list to controller-board

### PR DESCRIPTION
**Pull request by marcpfuller**
changed device name in devices list to controller-board

Signed-off-by: Marc-Philippe Fuller <marc-philippe.fuller@intel.com>

### CODE REVIEW

**Review by lenny-intel — APPROVED** [review]
LGTM, assuming that matches name used in the code... ;-)

**Comment by marcpfuller** [comment]
> LGTM, assuming that matches name used in the code... ;-)

Thanks for the reminder, I just did a search to see if there are any hard coded usage for the old device name and I found some.

**Review by brian-intel — APPROVED** [review]

**Review by lenny-intel — APPROVED** [review]
LGTM

**Review by brian-intel — APPROVED** [review]

**Comment by brian-intel** [comment]
LGTM

**Pull request merged**
