### PR TITLE
fix: upgrade gocv to the latest version 0.31.0 and openvino 2022.2

### PR DESCRIPTION
**Pull request by jim-wang-intel**
- Use the latest opencv 4.6.0 and gocv 0.31.0
- Openvino version 2022.2 on ubuntu 20 
- Use the latest Openvino IR model from open model zoo 

Signed-off-by: Jim Wang (Intel) <yutsung.jim.wang@intel.com>

### CODE REVIEW

**Review by lenny-intel — APPROVED** [review]
LGTM

**Comment by lenny-intel** [comment]
Add @antoniomtz as a reviewer

**Review by vli11 — COMMENTED** [review]
change looks good to me, we may not want to merge it into EdgeX2.2 branch since openvino update is another kind of release

**Review by brian-intel — APPROVED** [review]

**Comment by jim-wang-intel** [comment]
> change looks good to me, we may not want to merge it into EdgeX2.2 branch since openvino update is another kind of release

changed the merging into branch 2022.2 like @brian-intel suggested

**Comment by jim-wang-intel** [comment]
Note: branch 2022.2 is branched off from the current head of EdgeX-2.2 branch

**Review by vli11 — APPROVED** [review]

**Pull request merged**
